//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.29 at 12:59:29 AM CEST 
//

package de.nrw.hbz.deepzoomer.dzi;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the de.nrw.hbz.deepzoomer.dzi package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: de.nrw.hbz.deepzoomer.dzi
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Image }
	 * 
	 */
	public Image createImage() {
		return new Image();
	}

	/**
	 * Create an instance of {@link Image.Size }
	 * 
	 */
	public Image.Size createImageSize() {
		return new Image.Size();
	}

}
