//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.29 at 12:59:29 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.microsoft.com/deepzoom/2008", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.nrw.hbz.deepzoomer.dzi;
